[package]
name = "palaver"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "0.1.51"
axum = "0.2.8"
http = "0.2.5"
hyper = "0.14.13"
pulldown-cmark = { version = "0.8", default-features = false, features = ["simd"] }
tokio = { version = "1", features = ["full"] }
